add_rules("mode.release")
add_cflags("-ffreestanding", "-mcpu=arm920t", "-nostdlib")
add_cxxflags("-fno-exceptions", "-fno-rtti", "-ffreestanding", "-mcpu=arm920t", "-nostdlib")
add_ldflags("-nostdlib")
set_policy("build.optimization.lto", true)
set_languages("cxx23")
set_arch("arm")
set_plat("cross")
target("kernel")
  set_kind("binary")
  add_files("kernel.lds")
  add_files("src/main.cpp")
