add_rules("mode.release")
add_cxxflags("-fno-exceptions", "-fno-rtti", "-ffreestanding", "-mcpu=arm920t")
add_ldflags("-nostdlib")
set_policy("build.optimization.lto", true)
set_languages("cxx23")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
target("kernel")
  set_kind("binary")
  add_files("kernel.lds")
  add_files("src/start.s")
  add_files("src/cpu.s")
  add_files("src/**.cpp")
