add_rules("mode.debug", "mode.release")
add_cflags("-ffreestanding", "-mcpu=arm920t", "-O2", "-nostdlib")
add_cxxflags("-fno-exceptions", "-fno-rtti", "-ffreestanding", "-mcpu=arm920t", "-O2", "-nostdlib")
add_ldflags("-nostdlib")
set_arch("arm")
set_plat("cross")
target("kernel")
  set_kind("binary")
  add_files("kernel.lds")
  add_files("src/main.cpp")
